### ISSUE TITLE
Is there a EF Core DataProxy?

### ISSUE THREAD

**Issue by JGrzybowski** [ahanusa/Peasy.NET#13]
Hi, is there an EF Core implemetation of DataProxy? If not, is there any work started? 
I'm going to use Peasy in a couple of NET Core projects and could provide some help with it.

**Comment by ahanusa** [comment]
Man, that would be AWESOME, I've been swamped lately!  I'll create a repo
for it and add you as a contributor.

How much are you willing to tackle?

**Comment by JGrzybowski** [comment]
Sure! 
Just if would be nice to have some requirements (eg. transactions working etc.) 
As we know some of the features of classic EF are not there yet (like lazy loading) and it can help to see what we are able to do for now.

**Comment by ahanusa** [comment]
What database are you using?  I forgot that EF Core has different providers
now (sql server, sql lite, etc).

I don't think it makes sense to create one Peasy.DataProxy.EFCore project
anymore, but rather one project for each provider type.

**Comment by JGrzybowski** [comment]
It can make sense to create one.
But it should support the usual asp.net usage which means dbContext created
once per request. So you can't dispose the context after calling the method
from proxy. I'm in the middle of testing another way to get this compared
to the one that was in the EfCore repo.

04.02.2018 1:46 PM "Aaron Hanusa" <notifications@github.com> napisał(a):

**Comment by ahanusa** [comment]
Nice!  Let me know when you have something figured out.  Also, thanks for
the help, I really appreciate it!
