### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by andr01d** [ahanusa/Peasy.NET#19]
Which is the recommended way to catch exceptions, especially with databases (connections, data conflicts, etc.)?

**Comment by ahanusa** [comment]
Depending on the exception type, I generally find it best to let unhandled exceptions bubble up.  

The rules engine is mostly designed to deal with known things that can happen that you want to report on (ie. invalid data, business logic assertions, etc.).

Do you have a more specific case?

**Comment by andr01d** [comment]
The cases I'm interested is database exceptions (connections, data conflicts, etc)

**Comment by ahanusa** [comment]
Ok, then I would let them bubble up.
