### ISSUE TITLE
Get Appveyor build script working

### ISSUE THREAD

**Issue by ahanusa** [ahanusa/Peasy.NET#20]
For some reason appveyor can't build the test project.  Dig in to see why and fix.

**Comment by bruce-dunwiddie** [comment]
@ahanusa can you provide a link to the current build log?

**Comment by ahanusa** [comment]
Hi Bruce, thanks for reaching out!  We have recently converted tests to use XUnit, so I'm not sure that this issue will be relevant once things are merged into master.  I will definitely hit you up for help if it's still an issue.  I hope to have a new Peasy version released within the next week or two.  Thanks again, really appreciate it!
