### ISSUE TITLE
Should we remove synchronous support?

### ISSUE THREAD

**Issue by ahanusa** [ahanusa/Peasy.NET#21]
Hello all, we'd like to put a feeler out to see if people generally use the synchronous versions of Command, Rule, etc.?

Since it's inception, we have personally never used the synchronous version of any of these interfaces, and have always opted to use the asynchronous version.

That said, in an effort to reduce complexity, we would like to remove the synchronous support in peasy.

Are you using the synchronous api?

Can you think of a reason why it might not be a great idea to remove support for it, other than requiring a major version change?

Thanks for your thoughts!

**Comment by nadjibus** [comment]
For DataProxy, yes, synchronous calls are rarely used (if not at all). For validation though, I think it's the opposite, for me most validations are synchronous, rarely async (for eg. to check against an API or a DB record).

**Comment by ahanusa** [comment]
> For DataProxy, yes, synchronous calls are rarely used (if not at all). For validation though, I think it's the opposite, for me most validations are synchronous, rarely async (for eg. to check against an API or a DB record).

Thanks for the feedback!  If you are using synchronous validation, then you must be using the synchronous execution pipeline.  So for example:

`var result = command.Execute() --> loops through rules --> Rule.Validate() --> If all rules successful --> DataProxy.SynchronousMethod`

Here's a better [diagram](https://github.com/peasy/Peasy.NET/wiki/The-Synchronous-Pipeline)

You can contrast that with the [async pipeline diagram](https://github.com/peasy/Peasy.NET/wiki/The-Asynchronous-Pipeline)

So it sounds to me like you are using the synchronous pipeline and not the asynchronous pipeline, is that correct?

**Comment by nadjibus** [comment]
Ah yes, you're right, just got confused. Yes in that case I never used synchronous pipeline in real world projects (2 using Peasy atm)

**Comment by ahanusa** [comment]
> Ah yes, you're right, just got confused. Yes in that case I never used synchronous pipeline in real world projects (2 using Peasy atm)

Ohh, good!  It's hard to imagine that anyone is using the synchronous version, but I'm guessing there's someone using it with good reason.  Thanks again for your feedback, we really appreciate it!

**Comment by ahanusa** [comment]
Synchronous behavior will not be removed, but will now exist in synchronous specific classes in a new Peasy.Synchronous namespace.
