### ISSUE TITLE
Map validation rules to asp.net mvc validation

### ISSUE THREAD

**Issue by escobar5** [ahanusa/Peasy.NET#6]
I know this is independent of the presentation layer, but do you have any suggestions about how to map the validation rules of Peasy with Asp.Net MVC validation? and specially client validation.

**Comment by ahanusa** [comment]
Are you familiar with the peasy [samples](https://github.com/peasy/Samples) project?  There is a sample MVC app that showcases how you might handle this.  Let me know if the code is sufficient.

**Comment by ahanusa** [comment]
Hi Juan, did the samples project provide you with what you needed?

**Comment by escobar5** [comment]
Oh, what a nice and complete example. This should answer my question. Thank you.
